import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { BookOpen, Calculator, Check, CircleHelp, Gift, Gamepad2, Languages, LockKeyhole, Medal, Pause, Play, ShoppingBag, Sparkles, Star, Volume2 } from "lucide-react";
import { defaultChildContent, type ChildContentConfig, type StoreItemContent } from "../lib/child-content";

export type BoxOpening = { boxIndex: number; majorReward: number; selectedMajorIndex: number };
export type ChildRewardsState = { purchasedIds: string[]; openedBoxes: BoxOpening[]; lifetimePoints: number };
export const defaultChildRewards: ChildRewardsState = { purchasedIds: [], openedBoxes: [], lifetimePoints: 0 };
export function normalizeChildRewards(value: unknown): ChildRewardsState {
  if (!value || typeof value !== "object") return defaultChildRewards;
  const item = value as Partial<ChildRewardsState>;
  return { purchasedIds: Array.isArray(item.purchasedIds) ? item.purchasedIds.filter((id): id is string => typeof id === "string") : [], openedBoxes: Array.isArray(item.openedBoxes) ? item.openedBoxes.filter((box): box is BoxOpening => Boolean(box && typeof box === "object" && Number.isInteger((box as BoxOpening).boxIndex) && Number.isInteger((box as BoxOpening).majorReward) && Number.isInteger((box as BoxOpening).selectedMajorIndex))) : [], lifetimePoints: typeof item.lifetimePoints === "number" && Number.isFinite(item.lifetimePoints) ? Math.max(0, Math.floor(item.lifetimePoints)) : 0 };
}
type Props = { content?: ChildContentConfig; points: number; rewards: ChildRewardsState; onSpend: (cost: number, itemId: string) => boolean; onOpenBox: (opening: BoxOpening) => void; onAwardPoints: (amount: number) => void; onRequestChildUnlock: (onUnlocked: () => void) => void; childName?: string; childAvatar?: string };
const shuffle = <T,>(items: T[]) => { const copy = [...items]; for (let i = copy.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };
const fiftySession = <T,>(seeds: T[]) => shuffle(Array.from({ length: 50 }, (_, index) => seeds[index % seeds.length]));
const rewardIcon = (item: StoreItemContent) => item.kind === "money" ? Star : item.kind === "game" || item.kind === "screen" ? Gamepad2 : Gift;

export function ChildExtras({ content = defaultChildContent, points, rewards, onSpend, onOpenBox, onAwardPoints, onRequestChildUnlock, childName = "", childAvatar }: Props) {
  const [activePanel, setActivePanel] = useState<"letters" | "numbers" | "reading" | "store" | "badges" | null>(null);
  const [letterSession, setLetterSession] = useState<typeof content.letterGames>([]);
  const [letterIndex, setLetterIndex] = useState(0); const [letterAwarded, setLetterAwarded] = useState<Set<number>>(new Set()); const [letterMessage, setLetterMessage] = useState("");
  const [numberSession, setNumberSession] = useState<typeof content.numberQuestions>([]);
  const [numberIndex, setNumberIndex] = useState(0); const [numberAwarded, setNumberAwarded] = useState<Set<number>>(new Set()); const [numberAnswer, setNumberAnswer] = useState(""); const [numberMessage, setNumberMessage] = useState("");
  const [readingIndex, setReadingIndex] = useState(0); const [readingOpen, setReadingOpen] = useState(false); const [readingCompleted, setReadingCompleted] = useState<Set<string>>(new Set()); const [readingMessage, setReadingMessage] = useState(""); const [readingPausedUntil, setReadingPausedUntil] = useState(0); const [, setReaderTick] = useState(0); const [spokenWords, setSpokenWords] = useState(0); const [boxNotice, setBoxNotice] = useState("");
  const readingRef = useRef<HTMLDivElement>(null);
  const lifetimePoints = Math.max(points, rewards.lifetimePoints); const badgeCount = Math.floor(lifetimePoints / 120); const unlockedBoxes = Math.min(5, Math.floor(badgeCount / 3));
  const letter = letterSession[letterIndex]; const number = numberSession[numberIndex]; const story = content.readingStories[readingIndex] ?? content.readingStories[0]; const pauseRemaining = Math.max(0, Math.ceil((readingPausedUntil - Date.now()) / 1000));
  useEffect(() => {
    if (!readingOpen || readingPausedUntil > Date.now()) return;
    let animationFrame = 0;
    let previousTime: number | undefined;
    const rise = (time: number) => {
      if (previousTime !== undefined && readingRef.current) {
        const maxScroll = readingRef.current.scrollHeight - readingRef.current.clientHeight;
        readingRef.current.scrollTop = Math.min(maxScroll, readingRef.current.scrollTop + (time - previousTime) * 0.008);
      }
      previousTime = time;
      animationFrame = window.requestAnimationFrame(rise);
    };
    animationFrame = window.requestAnimationFrame(rise);
    return () => window.cancelAnimationFrame(animationFrame);
  }, [readingOpen, readingPausedUntil]);
  useEffect(() => { if (!readingOpen || readingPausedUntil <= Date.now()) return; const timer = window.setInterval(() => { setReaderTick((value) => value + 1); if (readingPausedUntil <= Date.now()) setReadingPausedUntil(0); }, 250); return () => window.clearInterval(timer); }, [readingOpen, readingPausedUntil]);
  const openPanel = (panel: NonNullable<typeof activePanel>) => { if (panel === "letters") { setLetterSession(fiftySession(content.letterGames).map((game) => ({ ...game, options: shuffle(game.options) }))); setLetterIndex(0); setLetterAwarded(new Set()); setLetterMessage(""); } if (panel === "numbers") { setNumberSession(fiftySession(content.numberQuestions)); setNumberIndex(0); setNumberAwarded(new Set()); setNumberAnswer(""); setNumberMessage(""); } setActivePanel(panel); };
  const requestPanel = (panel: NonNullable<typeof activePanel>) => {
    if (panel === "badges") openPanel(panel);
    else onRequestChildUnlock(() => openPanel(panel));
  };
  const chooseLetter = (answer: string) => { if (!letter) return; if (answer !== letter.answer) return setLetterMessage("جرّب مرة أخرى، أنت قريب!"); if (letterAwarded.has(letterIndex)) return setLetterMessage("أُضيفت نقاط هذه الإجابة بالفعل."); onAwardPoints(content.pointRewards.letterAnswer); setLetterAwarded((current) => new Set(current).add(letterIndex)); setLetterMessage(`إجابة صحيحة! حصلت على ${content.pointRewards.letterAnswer} نقاط.`); };
  const answerNumber = () => { if (!number) return; if (Number(numberAnswer) !== number.answer) return setNumberMessage("ليست الإجابة الصحيحة، راجع العملية بهدوء."); if (numberAwarded.has(numberIndex)) return; onAwardPoints(content.pointRewards.numberAnswer); setNumberAwarded((current) => new Set(current).add(numberIndex)); setNumberAnswer(""); if (numberIndex === 49) setNumberMessage(`أحسنت! أكملت 50 مسألة وحصلت على ${content.pointRewards.numberAnswer} نقاط للمسألة الأخيرة.`); else { setNumberIndex((value) => value + 1); setNumberMessage(`صحيح! حصلت على ${content.pointRewards.numberAnswer} نقاط. المسألة التالية تنتظرك.`); } };
  const openReading = (index: number) => { setReadingIndex(index); setReadingOpen(true); setSpokenWords(0); setReadingPausedUntil(0); setReadingMessage(""); window.setTimeout(() => { if (readingRef.current) readingRef.current.scrollTop = 0; }, 0); };
  const speakWord = (word: string) => { if (spokenWords >= 20 || !("speechSynthesis" in window)) return; const utterance = new SpeechSynthesisUtterance(word.replace(/[،.؟]/g, "")); utterance.lang = "ar-SA"; utterance.rate = .75; window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance); setSpokenWords((value) => value + 1); };
  const completeReading = () => { if (readingCompleted.has(story.id)) return setReadingMessage("أنهيت هذه القصة في هذه الجلسة بالفعل."); onAwardPoints(content.pointRewards.readingStory); setReadingCompleted((current) => new Set(current).add(story.id)); setReadingMessage(`أحسنت القراءة! حصلت على ${content.pointRewards.readingStory} نقاط.`); };
  const purchase = (itemId: string, cost: number) => { if (!rewards.purchasedIds.includes(itemId)) { if (!onSpend(cost, itemId)) setBoxNotice("تحتاج إلى نقاط أكثر لشراء هذه المكافأة."); else setBoxNotice("تم حفظ المكافأة في سجل ولي الأمر."); } };
  const openBox = (boxIndex: number) => { if (boxIndex >= unlockedBoxes || rewards.openedBoxes.some((item) => item.boxIndex === boxIndex)) return; const selectedMajorIndex = Math.floor(Math.random() * content.majorBoxRewards.length); const majorReward = content.majorBoxRewards[selectedMajorIndex]; onOpenBox({ boxIndex, majorReward, selectedMajorIndex }); setBoxNotice(`فتحت الصندوق وفزت بـ ${majorReward} ريال!`); };
  const readerWords = useMemo(() => story.text.split(/(\s+)/).filter(Boolean), [story.text]);
  const renderWord = (word: string) => Array.from(word).map((character, index) => <span className={/[\u064B-\u065F\u0670]/.test(character) ? "reader-diacritic" : "reader-base-letter"} key={`${character}-${index}`}>{character}</span>);
  const avatar = childAvatar || childName.trim().slice(0, 1) || "ب";
  return <section className="child-extras section-block" data-testid="panel-child-extras"><div className="section-heading"><div><h2>ساحة البطل</h2><p>ألعاب تعليمية ومكافآت إضافية بجانب تحديات المملكة.</p></div><span className="eyebrow"><Sparkles size={14} /> ميزات ملف الطفل</span></div>
    <div className="child-extras-grid">
      <button className="extra-feature-card letters-card protected-feature-card" data-testid="button-open-letter-games" onClick={() => requestPanel("letters")}><span className="extra-feature-icon"><Languages size={23} /></span><strong>درب الحروف</strong><span>جلسة جديدة من 50 سؤالاً.</span><em><LockKeyhole size={13} /> رمز الطفل لبدء اللعب</em></button>
      <button className="extra-feature-card numbers-card protected-feature-card" data-testid="button-open-number-cave" onClick={() => requestPanel("numbers")}><span className="extra-feature-icon"><Calculator size={23} /></span><strong>كهف الأرقام</strong><span>50 مسألة متنوعة في كل جلسة.</span><em><LockKeyhole size={13} /> رمز الطفل لبدء اللعب</em></button>
      <button className="extra-feature-card reading-card protected-feature-card" data-testid="button-open-reading-speed" onClick={() => requestPanel("reading")}><span className="extra-feature-icon"><BookOpen size={23} /></span><strong>القراءة السريعة</strong><span>قصص مشكولة مع تمرير هادئ ونطق الكلمات.</span><em><LockKeyhole size={13} /> رمز الطفل لفتح القصص</em></button>
      <button className="extra-feature-card store-card protected-feature-card" data-testid="button-open-reward-store" onClick={() => requestPanel("store")}><span className="extra-feature-icon"><ShoppingBag size={23} /></span><strong>متجر المكافآت</strong><span>حوّل نقاطك إلى مكافآت يراجعها ولي الأمر.</span><em><LockKeyhole size={13} /> رمز الطفل لفتح المتجر</em></button>
      <button className="extra-feature-card badges-card" data-testid="button-open-badges" onClick={() => openPanel("badges")}><span className="extra-feature-icon"><Medal size={23} /></span><strong>أوسمتي وصناديقي</strong><span>{badgeCount} وسام • {unlockedBoxes} من 5 صناديق مفتوحة</span><em>تقدم البطل <Star size={13} /></em></button>
    </div>
    {activePanel && createPortal(<div className="child-extras-overlay" role="dialog" aria-modal="true"><div className="child-extras-modal"><button className="icon-button child-extras-close" aria-label="إغلاق" onClick={() => setActivePanel(null)}>×</button>
      {activePanel === "letters" && letter && <div data-testid="panel-letter-games"><div className="extras-modal-heading"><Languages size={25} /><div><div className="eyebrow">درب الحروف</div><h2>اكتشف قوة الكلمات</h2></div></div><div className="letter-game-stage"><span className="game-stage-label">السؤال {letterIndex + 1} من 50</span><h3>{letter.question}</h3><p>{letter.description}</p><div className="answer-option-grid">{letter.options.map((option) => <button key={option} onClick={() => chooseLetter(option)} disabled={letterAwarded.has(letterIndex)}>{option}</button>)}</div>{letterMessage && <p className="game-message">{letterMessage}</p>}{letterAwarded.has(letterIndex) && letterIndex < 49 && <button className="primary-button gold" onClick={() => { setLetterIndex((value) => value + 1); setLetterMessage(""); }}>السؤال التالي</button>}</div></div>}
      {activePanel === "numbers" && number && <div data-testid="panel-number-cave"><div className="extras-modal-heading"><Calculator size={25} /><div><div className="eyebrow">كهف الأرقام</div><h2>حل المسألة</h2></div></div><div className="number-question"><span>المسألة {numberIndex + 1} من 50</span><strong>{number.prompt}</strong><div className="number-answer-row"><input data-testid="input-number-answer" inputMode="numeric" type="number" value={numberAnswer} onChange={(event) => setNumberAnswer(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") answerNumber(); }} disabled={numberAwarded.has(numberIndex)} autoFocus /><button className="primary-button gold" onClick={answerNumber} disabled={numberAwarded.has(numberIndex)}><Check size={16} /> تحقق</button></div>{numberMessage && <p className="game-message">{numberMessage}</p>}</div></div>}
      {activePanel === "reading" && <div data-testid="panel-reading-speed"><div className="extras-modal-heading"><BookOpen size={25} /><div><div className="eyebrow">القراءة السريعة</div><h2>اقرأ بهدوء وسرعة</h2></div></div>{!readingOpen ? <div className="story-grid">{content.readingStories.map((item, index) => <button key={item.id} onClick={() => openReading(index)}><BookOpen size={18} /><strong>{item.title}</strong><span>قصة مشكولة بالكامل</span></button>)}</div> : <div className="reader-stage"><div className="reader-toolbar"><button className="outline-button" onClick={() => setReadingOpen(false)}>كل القصص</button><span>نطق الكلمات: {spokenWords} / 20</span><button className="primary-button gold" onClick={() => setReadingPausedUntil(Date.now() + 10000)} disabled={pauseRemaining > 0}>{pauseRemaining > 0 ? `متوقف ${pauseRemaining} ث` : <><Pause size={15} /> إيقاف 10 ثوانٍ</>}</button></div><h3>{story.title}</h3><div className="reader-text reader-text-cairo" ref={readingRef}>{readerWords.map((word, index) => /\s/.test(word) ? word : <button key={`${word}-${index}`} className="reader-word" onClick={() => speakWord(word)} disabled={spokenWords >= 20}>{renderWord(word)}</button>)}</div><button className="primary-button gold complete-reading-button" disabled={readingCompleted.has(story.id)} onClick={completeReading}><Check size={16} /> {readingCompleted.has(story.id) ? "تم إكمال القصة" : `أكملت القراءة (+${content.pointRewards.readingStory})`}</button>{readingMessage && <p className="game-message">{readingMessage}</p>}<p className="reader-note"><Volume2 size={14} /> اضغط على الكلمات لسماع النطق. بقي لك {20 - spokenWords} كلمة.</p></div>}</div>}
      {activePanel === "store" && <div data-testid="panel-reward-store"><div className="extras-modal-heading"><ShoppingBag size={25} /><div><div className="eyebrow">متجر المكافآت</div><h2>ماذا تشتري بنقاطك؟</h2></div><strong className="store-balance">{points} نقطة</strong></div><div className="store-items-grid">{content.storeItems.map((item) => { const Icon = rewardIcon(item); const purchased = rewards.purchasedIds.includes(item.id); return <div className={`store-item ${purchased ? "purchased" : ""}`} key={item.id}><span className="store-child-avatar">{avatar}</span><span className="store-item-icon"><Icon size={19} /></span><strong>{item.title}</strong><span className="store-cost">{item.cost} نقطة</span><button className={purchased ? "outline-button" : "primary-button gold"} disabled={purchased || points < item.cost} onClick={() => purchase(item.id, item.cost)}>{purchased ? <><Check size={14} /> تم الطلب</> : "استبدال"}</button></div>; })}</div>{boxNotice && <p className="game-message">{boxNotice}</p>}</div>}
      {activePanel === "badges" && <div data-testid="panel-badges"><div className="extras-modal-heading"><Medal size={25} /><div><div className="eyebrow">رحلة الأوسمة</div><h2>كل 120 نقطة وسام جديد</h2></div></div><div className="badge-progress-list">{[0, 1, 2].map((index) => { const target = (index + 1) * 120; const progress = Math.min(100, Math.max(0, lifetimePoints - index * 120) / 120 * 100); return <div className="badge-progress-item" key={target}><Medal size={28} /><div><strong>الوسام {index + 1} — {target} نقطة</strong><span>{Math.round(progress)}%</span><div className="badge-track"><i style={{ width: `${progress}%` }} /></div></div></div>; })}</div><div className="mystery-boxes">{Array.from({ length: 5 }, (_, index) => { const opening = rewards.openedBoxes.find((item) => item.boxIndex === index); const available = index < unlockedBoxes; return <button key={index} className={`mystery-box ${available ? "available" : ""} ${opening ? "opened" : ""}`} disabled={!available || Boolean(opening)} onClick={() => openBox(index)}>{opening ? <><Gift size={25} /><strong>{opening.majorReward} ريال</strong></> : <><Gift size={25} /><strong>{available ? "افتحني" : <LockKeyhole size={18} />}</strong><span>الصندوق {index + 1}</span></>}</button>; })}</div>{rewards.openedBoxes.length > 0 && <div className="box-reveal-note"><CircleHelp size={16} /><span>الجوائز الكبرى المتاحة عشوائياً: {content.majorBoxRewards.join(" أو ")} ريال.</span></div>}</div>}
    </div></div>, document.body)}</section>;
}