import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { BookOpen, Check, CircleHelp, Gift, Gamepad2, LockKeyhole, Medal, Pause, ShoppingBag, Sparkles, Star, Volume2 } from "lucide-react";
import { defaultChildContent, type ChildContentConfig, type StoreItemContent } from "../lib/child-content";

export type BoxOpening = { boxIndex: number; majorReward: number; selectedMajorIndex: number };
export type ChildRewardsState = { purchasedIds: string[]; openedBoxes: BoxOpening[]; lifetimePoints: number };
export const defaultChildRewards: ChildRewardsState = { purchasedIds: [], openedBoxes: [], lifetimePoints: 0 };
export function normalizeChildRewards(value: unknown): ChildRewardsState {
  if (!value || typeof value !== "object") return defaultChildRewards;
  const item = value as Partial<ChildRewardsState>;
  return { purchasedIds: Array.isArray(item.purchasedIds) ? item.purchasedIds.filter((id): id is string => typeof id === "string") : [], openedBoxes: Array.isArray(item.openedBoxes) ? item.openedBoxes.filter((box): box is BoxOpening => Boolean(box && typeof box === "object" && Number.isInteger((box as BoxOpening).boxIndex) && Number.isInteger((box as BoxOpening).majorReward) && Number.isInteger((box as BoxOpening).selectedMajorIndex))) : [], lifetimePoints: typeof item.lifetimePoints === "number" && Number.isFinite(item.lifetimePoints) ? Math.max(0, Math.floor(item.lifetimePoints)) : 0 };
}
type Props = { content?: ChildContentConfig; points: number; rewards: ChildRewardsState; onSpend: (cost: number, itemId: string) => boolean; onOpenBox: (opening: BoxOpening) => void; onAwardPoints: (amount: number) => void; childName?: string; childAvatar?: string };
const rewardIcon = (item: StoreItemContent) => item.kind === "money" ? Star : item.kind === "game" || item.kind === "screen" ? Gamepad2 : Gift;

export function ChildExtras({ content = defaultChildContent, points, rewards, onSpend, onOpenBox, onAwardPoints, childName = "", childAvatar }: Props) {
  const [activePanel, setActivePanel] = useState<"reading" | "store" | "badges" | null>(null);
  const [readingIndex, setReadingIndex] = useState(0); const [readingOpen, setReadingOpen] = useState(false); const [readingCompleted, setReadingCompleted] = useState<Set<string>>(new Set()); const [readingMessage, setReadingMessage] = useState(""); const [readingPausedUntil, setReadingPausedUntil] = useState(0); const [, setReaderTick] = useState(0); const [spokenWords, setSpokenWords] = useState(0); const [boxNotice, setBoxNotice] = useState("");
  const readingRef = useRef<HTMLDivElement>(null);
  const lifetimePoints = Math.max(points, rewards.lifetimePoints); const badgeCount = Math.floor(lifetimePoints / 120); const unlockedBoxes = Math.min(5, Math.floor(badgeCount / 3));
  const story = content.readingStories[readingIndex] ?? content.readingStories[0]; const pauseRemaining = Math.max(0, Math.ceil((readingPausedUntil - Date.now()) / 1000));
  useEffect(() => {
    if (!readingOpen || readingPausedUntil > Date.now()) return;
    let animationFrame = 0;
    let previousTime: number | undefined;
    const rise = (time: number) => {
      if (previousTime !== undefined && readingRef.current) {
          const maxScroll = readingRef.current.scrollHeight - readingRef.current.clientHeight;
          const nextScroll = readingRef.current.scrollTop + (time - previousTime) * 0.008;
          readingRef.current.scrollTop = nextScroll >= maxScroll ? 0 : nextScroll;
      }
      previousTime = time;
      animationFrame = window.requestAnimationFrame(rise);
    };
    animationFrame = window.requestAnimationFrame(rise);
    return () => window.cancelAnimationFrame(animationFrame);
  }, [readingOpen, readingPausedUntil]);
  useEffect(() => { if (!readingOpen || readingPausedUntil <= Date.now()) return; const timer = window.setInterval(() => { setReaderTick((value) => value + 1); if (readingPausedUntil <= Date.now()) setReadingPausedUntil(0); }, 250); return () => window.clearInterval(timer); }, [readingOpen, readingPausedUntil]);
  const openPanel = (panel: NonNullable<typeof activePanel>) => setActivePanel(panel);
  const openReading = (index: number) => { setReadingIndex(index); setReadingOpen(true); setSpokenWords(0); setReadingPausedUntil(0); setReadingMessage(""); window.setTimeout(() => { if (readingRef.current) readingRef.current.scrollTop = 0; }, 0); };
  const speakWord = (word: string) => { if (spokenWords >= 20 || !("speechSynthesis" in window)) return; const utterance = new SpeechSynthesisUtterance(word.replace(/[،.؟]/g, "")); utterance.lang = "ar-SA"; utterance.rate = .75; window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance); setSpokenWords((value) => value + 1); };
  const completeReading = () => { if (readingCompleted.has(story.id)) return setReadingMessage("أنهيت هذه القصة في هذه الجلسة بالفعل."); onAwardPoints(content.pointRewards.readingStory); setReadingCompleted((current) => new Set(current).add(story.id)); setReadingMessage(`أحسنت القراءة! حصلت على ${content.pointRewards.readingStory} نقاط.`); };
  const purchase = (itemId: string, cost: number) => { if (!rewards.purchasedIds.includes(itemId)) { if (!onSpend(cost, itemId)) setBoxNotice("تحتاج إلى نقاط أكثر لشراء هذه المكافأة."); else setBoxNotice("تم حفظ المكافأة في سجل ولي الأمر."); } };
  const openBox = (boxIndex: number) => { if (boxIndex >= unlockedBoxes || rewards.openedBoxes.some((item) => item.boxIndex === boxIndex)) return; const selectedMajorIndex = Math.floor(Math.random() * content.majorBoxRewards.length); const majorReward = content.majorBoxRewards[selectedMajorIndex]; onOpenBox({ boxIndex, majorReward, selectedMajorIndex }); setBoxNotice(`فتحت الصندوق وفزت بـ ${majorReward} ريال!`); };
  const readerWords = useMemo(() => story.text.split(/(\s+)/).filter(Boolean), [story.text]);
  const renderWord = (word: string) => Array.from(word).map((character, index) => <span className={/[\u064B-\u065F\u0670]/.test(character) ? "reader-diacritic" : "reader-base-letter"} key={`${character}-${index}`}>{character}</span>);
  const avatar = childAvatar || childName.trim().slice(0, 1) || "ب";
  return <section className="child-extras section-block" data-testid="panel-child-extras"><div className="section-heading"><div><h2>ساحة البطل</h2><p>ألعاب تعليمية ومكافآت إضافية بجانب تحديات المملكة.</p></div><span className="eyebrow"><Sparkles size={14} /> ميزات ملف الطفل</span></div>
    <div className="child-extras-grid">
      <button className="extra-feature-card reading-card" data-testid="button-open-reading-speed" onClick={() => openPanel("reading")}><span className="extra-feature-icon"><BookOpen size={23} /></span><strong>القراءة السريعة</strong><span>قصص مشكولة مع تمرير هادئ ونطق الكلمات.</span></button>
      <button className="extra-feature-card store-card" data-testid="button-open-reward-store" onClick={() => openPanel("store")}><span className="extra-feature-icon"><ShoppingBag size={23} /></span><strong>متجر المكافآت</strong><span>حوّل نقاطك إلى مكافآت يراجعها ولي الأمر.</span></button>
      <button className="extra-feature-card badges-card" data-testid="button-open-badges" onClick={() => openPanel("badges")}><span className="extra-feature-icon"><Medal size={23} /></span><strong>أوسمتي وصناديقي</strong><span>{badgeCount} وسام • {unlockedBoxes} من 5 صناديق مفتوحة</span><em>تقدم البطل <Star size={13} /></em></button>
    </div>
    {activePanel && createPortal(<div className="child-extras-overlay" role="dialog" aria-modal="true"><div className="child-extras-modal"><button className="icon-button child-extras-close" aria-label="إغلاق" onClick={() => setActivePanel(null)}>×</button>
      {activePanel === "reading" && <div data-testid="panel-reading-speed"><div className="extras-modal-heading"><BookOpen size={25} /><div><div className="eyebrow">القراءة السريعة</div><h2>اقرأ بهدوء وسرعة</h2></div></div>{!readingOpen ? <div className="story-grid">{content.readingStories.map((item, index) => <button key={item.id} onClick={() => openReading(index)}><BookOpen size={18} /><strong>{item.title}</strong><span>قصة مشكولة بالكامل</span></button>)}</div> : <div className="reader-stage"><div className="reader-toolbar"><button className="outline-button" onClick={() => setReadingOpen(false)}>كل القصص</button><span>نطق الكلمات: {spokenWords} / 20</span><button className="primary-button gold" onClick={() => setReadingPausedUntil(Date.now() + 10000)} disabled={pauseRemaining > 0}>{pauseRemaining > 0 ? `متوقف ${pauseRemaining} ث` : <><Pause size={15} /> إيقاف 10 ثوانٍ</>}</button></div><h3>{story.title}</h3><div className="reader-text reader-text-cairo" ref={readingRef}>{readerWords.map((word, index) => /\s/.test(word) ? word : <button key={`${word}-${index}`} className="reader-word" onClick={() => speakWord(word)} disabled={spokenWords >= 20}>{renderWord(word)}</button>)}</div><button className="primary-button gold complete-reading-button" disabled={readingCompleted.has(story.id)} onClick={completeReading}><Check size={16} /> {readingCompleted.has(story.id) ? "تم إكمال القصة" : `أكملت القراءة (+${content.pointRewards.readingStory})`}</button>{readingMessage && <p className="game-message">{readingMessage}</p>}<p className="reader-note"><Volume2 size={14} /> اضغط على الكلمات لسماع النطق. بقي لك {20 - spokenWords} كلمة.</p></div>}</div>}
      {activePanel === "store" && <div data-testid="panel-reward-store"><div className="extras-modal-heading"><ShoppingBag size={25} /><div><div className="eyebrow">متجر المكافآت</div><h2>ماذا تشتري بنقاطك؟</h2></div><strong className="store-balance">{points} نقطة</strong></div><div className="store-items-grid">{content.storeItems.map((item) => { const Icon = rewardIcon(item); const purchased = rewards.purchasedIds.includes(item.id); return <div className={`store-item ${purchased ? "purchased" : ""}`} key={item.id}><span className="store-child-avatar">{avatar}</span><span className="store-item-icon"><Icon size={19} /></span><strong>{item.title}</strong><span className="store-cost">{item.cost} نقطة</span><button className={purchased ? "outline-button" : "primary-button gold"} disabled={purchased || points < item.cost} onClick={() => purchase(item.id, item.cost)}>{purchased ? <><Check size={14} /> تم الطلب</> : "استبدال"}</button></div>; })}</div>{boxNotice && <p className="game-message">{boxNotice}</p>}</div>}
      {activePanel === "badges" && <div data-testid="panel-badges"><div className="extras-modal-heading"><Medal size={25} /><div><div className="eyebrow">رحلة الأوسمة</div><h2>كل 120 نقطة وسام جديد</h2></div></div><div className="badge-progress-list">{[0, 1, 2].map((index) => { const target = (index + 1) * 120; const progress = Math.min(100, Math.max(0, lifetimePoints - index * 120) / 120 * 100); return <div className="badge-progress-item" key={target}><Medal size={28} /><div><strong>الوسام {index + 1} — {target} نقطة</strong><span>{Math.round(progress)}%</span><div className="badge-track"><i style={{ width: `${progress}%` }} /></div></div></div>; })}</div><div className="mystery-boxes">{Array.from({ length: 5 }, (_, index) => { const opening = rewards.openedBoxes.find((item) => item.boxIndex === index); const available = index < unlockedBoxes; return <button key={index} className={`mystery-box ${available ? "available" : ""} ${opening ? "opened" : ""}`} disabled={!available || Boolean(opening)} onClick={() => openBox(index)}>{opening ? <><Gift size={25} /><strong>{opening.majorReward} ريال</strong></> : <><Gift size={25} /><strong>{available ? "افتحني" : <LockKeyhole size={18} />}</strong><span>الصندوق {index + 1}</span></>}</button>; })}</div>{rewards.openedBoxes.length > 0 && <div className="box-reveal-note"><CircleHelp size={16} /><span>الجوائز الكبرى المتاحة عشوائياً: {content.majorBoxRewards.join(" أو ")} ريال.</span></div>}</div>}
    </div></div>, document.body)}</section>;
}